name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull stekajack/ubuntults_with_espresso_magnetodynamics_wip

      - name: Run tests & generate coverage report
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            stekajack/ubuntults_with_espresso_magnetodynamics_wip \
            bash -c "
              pip3 install -e . coverage &&
              coverage run --branch --source=pressomancy -m unittest discover -s test &&
              coverage xml -o coverage.xml
            "

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true